begin;

insert into public.shipping_city_mappings (
  provider,
  provider_city_id,
  governorate,
  city,
  city_arabic
)
values
  ('pdc', 1, 'Cairo', 'Al Herafiyeen', 'الحرفيين'),
  ('pdc', 2, 'Cairo', 'Zamalek', 'الزمالك'),
  ('pdc', 3, 'Cairo', 'Boulak abul-Ela', 'بولاق أبو العلا'),
  ('pdc', 4, 'Cairo', 'Down Town', 'وسط البلد'),
  ('pdc', 5, 'Cairo', 'Garden City', 'جاردن سيتي'),
  ('pdc', 6, 'Cairo', 'Manial', 'المنيل'),
  ('pdc', 7, 'Cairo', 'Attaba', 'العتبه'),
  ('pdc', 8, 'Cairo', 'Qasr el-Einy', 'القصر العيني'),
  ('pdc', 9, 'Cairo', 'Dhaher', 'الظاهر'),
  ('pdc', 10, 'Cairo', 'Ramses', 'رمسيس'),
  ('pdc', 11, 'Cairo', 'Shoubra Masr', 'شبرا مصر'),
  ('pdc', 12, 'Cairo', 'Darrasa', 'الدراسة'),
  ('pdc', 13, 'Cairo', 'Abbassiya', 'العباسية'),
  ('pdc', 14, 'Cairo', 'Darb el-Ahmar', 'الدرب الأحمر'),
  ('pdc', 15, 'Cairo', 'Bab el-Shiriya', 'باب الشعرية'),
  ('pdc', 16, 'Cairo', 'Sayeda Zeinab', 'السيدة زينب'),
  ('pdc', 17, 'Cairo', 'Old Cairo', 'مصر القديمة'),
  ('pdc', 18, 'Cairo', 'Nasr City', 'مدينة نصر'),
  ('pdc', 19, 'Cairo', '10th District', 'الحى العاشر'),
  ('pdc', 20, 'Cairo', 'Heliopolis', 'مصر الجديدة'),
  ('pdc', 21, 'Cairo', 'Gesr el-Suez', 'جسر السويس'),
  ('pdc', 22, 'Cairo', 'Alf Maskan', 'الألف مسكن'),
  ('pdc', 23, 'Cairo', 'Obour Buildings', 'عمارات العبور'),
  ('pdc', 24, 'Cairo', 'Ard el-Golf', 'ارض الجولف'),
  ('pdc', 25, 'Cairo', 'Hadayek el-Qobba', 'حدائق القبة'),
  ('pdc', 26, 'Cairo', 'Zaytoun', 'الزيتون'),
  ('pdc', 27, 'Cairo', 'Ameeriya', 'الأميرية'),
  ('pdc', 28, 'Cairo', 'Matariya', 'المطرية'),
  ('pdc', 29, 'Cairo', 'Ain Shams', 'عين شمس'),
  ('pdc', 30, 'Cairo', 'New Maadi', 'المعادي الجديدة'),
  ('pdc', 31, 'Cairo', 'Dar el-Salam', 'دار السلام'),
  ('pdc', 32, 'Cairo', 'Maadi', 'المعادي'),
  ('pdc', 33, 'Cairo', 'Moqattam', 'المقطم'),
  ('pdc', 34, 'Cairo', 'El-Hadaba el-Sofla', 'الهضبة السفلى'),
  ('pdc', 35, 'Cairo', 'Tora', 'طرة'),
  ('pdc', 36, 'Cairo', 'Maasara', 'المعصرة'),
  ('pdc', 37, 'Cairo', 'Helwan', 'حلوان'),
  ('pdc', 38, 'Cairo', 'Kotsica', 'كوتسيكا'),
  ('pdc', 39, 'Cairo', 'Qattamiya', 'القطامية'),
  ('pdc', 40, 'Cairo', 'New Cairo', 'التجمع'),
  ('pdc', 41, 'Cairo', 'El Rehab', 'الرحاب'),
  ('pdc', 42, 'Cairo', 'Madinty', 'مدينتى'),
  ('pdc', 43, 'Cairo', 'Cairo Airport', 'مطار القاهرة'),
  ('pdc', 44, 'Cairo', 'Salam City', 'مدينة السلام'),
  ('pdc', 45, 'Cairo', 'Obour City', 'مدينة العبور'),
  ('pdc', 46, 'Cairo', 'Ezbet el-Haganna', 'عزبة الهجانة'),
  ('pdc', 47, 'Cairo', 'Tibeen', 'التبين'),
  ('pdc', 48, 'Cairo', '15th of May City', 'مدينة 15 مايو'),
  ('pdc', 49, 'Cairo', 'Badr City', 'مدينة بدر'),
  ('pdc', 50, 'Cairo', 'Shourouq City', 'الشروق'),
  ('pdc', 51, 'Giza', 'Dokki', 'الدقي'),
  ('pdc', 52, 'Giza', 'Mohandiseen', 'المهندسين'),
  ('pdc', 53, 'Giza', 'Agouza', 'العجوزة'),
  ('pdc', 54, 'Giza', 'Ard-el-Lewa', 'ارض اللواء'),
  ('pdc', 55, 'Giza', 'Matar Imbaba', 'مطار امبابه'),
  ('pdc', 56, 'Giza', 'Saft-e-Laban', 'صفط اللبن'),
  ('pdc', 57, 'Giza', 'Imbaba', 'امبابة'),
  ('pdc', 58, 'Giza', 'Warraq', 'الوراق'),
  ('pdc', 59, 'Giza', 'Bashteel', 'بشتيل'),
  ('pdc', 60, 'Giza', 'Boulak-e-Dakrour', 'بولاق الدكرور'),
  ('pdc', 61, 'Giza', 'Giza', 'الجيزة'),
  ('pdc', 62, 'Giza', 'Faisal', 'فيصل'),
  ('pdc', 63, 'Giza', 'Haram', 'الهرم'),
  ('pdc', 64, 'Giza', 'Monieb', 'المنيب'),
  ('pdc', 65, 'Giza', 'Ahram Gardens', 'حدائق الأهرام'),
  ('pdc', 66, 'Giza', 'Rimaya', 'الرماية'),
  ('pdc', 67, 'Giza', '6th of October', 'مدينة 6 أكتوبر'),
  ('pdc', 68, 'Giza', 'Sheikh Zayed', 'مدينة الشيخ زايد'),
  ('pdc', 69, 'Giza', 'Wahat Road', 'طريق الواحات'),
  ('pdc', 70, 'Giza', 'Alex desert road till KM 28', 'طريق إسكندرية الصحراوى حتى ك 28'),
  ('pdc', 71, 'Giza', 'Smart Village', 'القرية الذكية'),
  ('pdc', 72, 'Giza', 'Nahiya', 'ناهيا البلد'),
  ('pdc', 73, 'Giza', 'Kafr Hakeem', 'كفر حكيم'),
  ('pdc', 74, 'Giza', 'Abu Rawash', 'أبو رواش'),
  ('pdc', 75, 'Giza', 'Saqqara', 'سقارة'),
  ('pdc', 76, 'Giza', 'Manial Sheeha', 'منيل شيحة'),
  ('pdc', 77, 'Giza', 'El-Manawat', 'المنوات'),
  ('pdc', 78, 'Alexandria', 'Sidi Gaber', 'سيدي جابر'),
  ('pdc', 79, 'Alexandria', 'Moharram Bek', 'محرم بك'),
  ('pdc', 80, 'Alexandria', 'Mina El-Basal', 'مينا البصل'),
  ('pdc', 81, 'Alexandria', 'Al Raml', 'الرمل'),
  ('pdc', 82, 'Alexandria', 'Al Montaza', 'المنتزه'),
  ('pdc', 83, 'Alexandria', 'Al Mansheya', 'المنشية'),
  ('pdc', 84, 'Alexandria', 'Al Labban', 'اللبان'),
  ('pdc', 85, 'Alexandria', 'Qetaa Maryout', 'قطاع مريوط'),
  ('pdc', 86, 'Alexandria', 'Qetaa at Tarik Al Sahrawi', 'قطاع الطريق الصحراوي'),
  ('pdc', 87, 'Alexandria', 'Bab Sharqi', 'باب شرقي'),
  ('pdc', 88, 'Alexandria', 'Al Gomrok', 'الجمرك'),
  ('pdc', 89, 'Alexandria', 'Al Attarin', 'العطارين'),
  ('pdc', 90, 'Alexandria', 'New Borg Al Arab', 'برج العرب الجديدة'),
  ('pdc', 91, 'Alexandria', 'Karmouz', 'كرموز'),
  ('pdc', 92, 'Alexandria', 'Al king maryout (Sharq & Gharb)', 'كينج مريوط (شرق وغرب)'),
  ('pdc', 93, 'Alexandria', 'Dekhela', 'الدخيلة'),
  ('pdc', 94, 'Alexandria', 'Borg Al Arab', 'برج العرب'),
  ('pdc', 95, 'Alexandria', 'Alexandria Desert', 'الطريق الصحراوي'),
  ('pdc', 96, 'Alexandria', 'Al Amaria First', 'العامرية أول'),
  ('pdc', 97, 'Alexandria', 'Al Daerah Al Gomrokeyah', 'الدائرة الجمركية'),
  ('pdc', 98, 'Alexandria 2', 'North Coast', 'الساحل الشمالي'),
  ('pdc', 99, 'Al Behaira', 'Shabrakhit', 'شبراخيت'),
  ('pdc', 100, 'Al Behaira', 'Rashid', 'رشيد'),
  ('pdc', 101, 'Al Behaira', 'Mahmoudiyah', 'المحمودية'),
  ('pdc', 102, 'Al Behaira', 'Kom Hamada', 'كوم حمادة'),
  ('pdc', 103, 'Al Behaira', 'Kafr Al Dawwar', 'كفر الدوار'),
  ('pdc', 104, 'Al Behaira', 'Itay Al Baroud', 'إيتاي البارود'),
  ('pdc', 105, 'Al Behaira', 'Hosh Issa', 'حوش عيسى'),
  ('pdc', 106, 'Al Behaira', 'Edco', 'إدكو'),
  ('pdc', 107, 'Al Behaira', 'Damanhour', 'دمنهور'),
  ('pdc', 108, 'Al Behaira', 'Badr', 'بدر'),
  ('pdc', 109, 'Al Behaira', 'Al delengaat', 'الدلنجات'),
  ('pdc', 110, 'Al Behaira', 'Al Rahmaniyah', 'الرحمانية'),
  ('pdc', 111, 'Al Behaira', 'Al Nubaria al-gedida', 'النوبارية الجديدة'),
  ('pdc', 112, 'Al Behaira', 'Al Behaira', 'البحيرة'),
  ('pdc', 113, 'Al Behaira', 'Abu Hummus', 'أبو حمص'),
  ('pdc', 114, 'Al Behaira', 'Abu al-Matamir', 'أبو المطامير'),
  ('pdc', 115, 'Al Behaira', 'Wadi', 'وادي'),
  ('pdc', 116, 'Al Mounofia', 'Tella', 'تلا'),
  ('pdc', 117, 'Al Mounofia', 'Shebeen Alkom', 'شبين الكوم'),
  ('pdc', 118, 'Al Mounofia', 'Sarss', 'سرس'),
  ('pdc', 119, 'Al Mounofia', 'Qwessna', 'قويسنا'),
  ('pdc', 120, 'Al Mounofia', 'Menouf', 'منوف'),
  ('pdc', 121, 'Al Mounofia', 'Hay Sharq', 'حي شرق'),
  ('pdc', 122, 'Al Mounofia', 'Hay Gharb', 'حي غرب'),
  ('pdc', 123, 'Al Mounofia', 'Ashmoun', 'أشمون'),
  ('pdc', 124, 'Al Mounofia', 'Al shouhdaa', 'الشهداء'),
  ('pdc', 125, 'Al Mounofia', 'Al sadat', 'السادات'),
  ('pdc', 126, 'Al Mounofia', 'Al bagour', 'الباجور'),
  ('pdc', 127, 'Algharbia', 'Al Mahalla el', 'المحلة'),
  ('pdc', 128, 'Algharbia', 'Tanta', 'طنطا'),
  ('pdc', 129, 'Algharbia', 'Kafr Al Zayat', 'كفر الزيات'),
  ('pdc', 130, 'Algharbia', 'Samannoud', 'سمنود'),
  ('pdc', 131, 'Algharbia', 'Zifta', 'زفتى'),
  ('pdc', 132, 'Algharbia', 'Basyoun', 'بسيون'),
  ('pdc', 133, 'Algharbia', 'Desouk', 'دسوق'),
  ('pdc', 134, 'Dakhahlia', 'Tami Alamdid', 'تمي الأمديد'),
  ('pdc', 135, 'Dakhahlia', 'Talkha', 'طلخا'),
  ('pdc', 136, 'Dakhahlia', 'Sherbeen', 'شربين'),
  ('pdc', 137, 'Dakhahlia', 'Meniat Al Nassr', 'منية النصر'),
  ('pdc', 138, 'Dakhahlia', 'Meit Ghamr', 'ميت غمر'),
  ('pdc', 139, 'Dakhahlia', 'Meit Salseil', 'ميت سلسيل'),
  ('pdc', 140, 'Dakhahlia', 'Mahla Demna', 'محلة دمنة'),
  ('pdc', 141, 'Dakhahlia', 'Gamassa', 'جمصة'),
  ('pdc', 142, 'Dakhahlia', 'Dekerness', 'دكرنس'),
  ('pdc', 143, 'Dakhahlia', 'Dakhahlia', 'الدقهلية'),
  ('pdc', 144, 'Dakhahlia', 'Belqass', 'بلقاس'),
  ('pdc', 145, 'Dakhahlia', 'Bani Ebeid', 'بني عبيد'),
  ('pdc', 146, 'Dakhahlia', 'Banbro', 'منية النصر'),
  ('pdc', 147, 'Dakhahlia', 'Al senbelaween', 'السنبلاوين'),
  ('pdc', 148, 'Dakhahlia', 'Al matria', 'المطرية'),
  ('pdc', 149, 'Dakhahlia', 'Al gamlia', 'الجمالية'),
  ('pdc', 150, 'Dakhahlia', 'Al Qourdi', 'الكردي'),
  ('pdc', 151, 'Dakhahlia', 'Al Manzala', 'المنزلة'),
  ('pdc', 152, 'Dakhahlia', 'Al Mansoura', 'المنصورة'),
  ('pdc', 153, 'Dakhahlia', 'Aga', 'أجا'),
  ('pdc', 154, 'Dammitta', 'Rass Al Bar', 'رأس البر'),
  ('pdc', 155, 'Dammitta', 'Meet Abu Ghaleb', 'ميت أبو غالب'),
  ('pdc', 156, 'Dammitta', 'Kafr Saad', 'كفر سعد'),
  ('pdc', 157, 'Dammitta', 'Kafr Albatekh', 'كفر البطيخ'),
  ('pdc', 158, 'Dammitta', 'Faraskour', 'فارسكور'),
  ('pdc', 159, 'Dammitta', 'Ezbat Al Borg', 'عزبة البرج'),
  ('pdc', 160, 'Dammitta', 'Damietta  Al Gedida', 'دمياط الجديدة'),
  ('pdc', 161, 'Dammitta', 'Dammitta', 'دمياط'),
  ('pdc', 162, 'Dammitta', 'Al zarqa', 'الزرقا'),
  ('pdc', 163, 'Dammitta', 'Al rawda', 'الروضة'),
  ('pdc', 164, 'Dammitta', 'Al Serou', 'السرو'),
  ('pdc', 165, 'Elsharqia', 'Zaqazeq', 'الزقازيق'),
  ('pdc', 166, 'Elsharqia', 'San Al Hagar Alqeblia', 'صان الحجر القبلية'),
  ('pdc', 167, 'Elsharqia', 'Monshaet Abu Omar', 'منشأة أبو عمر'),
  ('pdc', 168, 'Elsharqia', 'Menia Al Qamh', 'منيا القمح'),
  ('pdc', 169, 'Elsharqia', 'Mashtoul Alsouk', 'مشتول السوق'),
  ('pdc', 170, 'Elsharqia', 'Kafr Sakr', 'كفر صقر'),
  ('pdc', 171, 'Elsharqia', 'Hehia', 'ههيا'),
  ('pdc', 172, 'Elsharqia', 'faqouss', 'فاقوس'),
  ('pdc', 173, 'Elsharqia', 'Derb Negm', 'ديرب نجم'),
  ('pdc', 174, 'Elsharqia', 'Belbass', 'بلبيس'),
  ('pdc', 175, 'Elsharqia', 'Awlaad sakr', 'أولاد صقر'),
  ('pdc', 176, 'Elsharqia', 'Alsalhia Algedieda', 'الصالحية الجديدة'),
  ('pdc', 177, 'Elsharqia', 'Alqarein', 'القرين'),
  ('pdc', 178, 'Elsharqia', 'Alqaniaat', 'القنايات'),
  ('pdc', 179, 'Elsharqia', 'Al Ibrahemia', 'الإبراهيمية'),
  ('pdc', 180, 'Elsharqia', 'Al Hussania', 'الحسينية'),
  ('pdc', 181, 'Elsharqia', 'Abu Kbeir', 'أبو كبير'),
  ('pdc', 182, 'Elsharqia', 'Abu Hamaad', 'أبو حماد'),
  ('pdc', 183, 'Elsharqia', '10th of Ramadan city', 'مدينة العاشر من رمضان'),
  ('pdc', 184, 'Elsharqia', 'Elsharqia', 'الشرقية'),
  ('pdc', 185, 'Ismalia', 'Qantara Sharq', 'القنطرة شرق'),
  ('pdc', 186, 'Ismalia', 'Ismalia', 'الإسماعيلية'),
  ('pdc', 187, 'Ismalia', 'Fayed', 'فايد'),
  ('pdc', 188, 'Ismalia', 'alqasaasayn', 'القصاصين'),
  ('pdc', 189, 'Ismalia', 'Alahyaa Alawal Althany - Althaless', 'الأحياء الأول والثاني والثالث'),
  ('pdc', 190, 'Ismalia', 'Al Tall Al Kbier', 'التل الكبير'),
  ('pdc', 191, 'Ismalia', 'Abu Sir', 'أبو صوير'),
  ('pdc', 192, 'kafr Al Sheikh', 'Sedi Salem', 'سيدي سالم'),
  ('pdc', 193, 'kafr Al Sheikh', 'Sedi Ghazi', 'سيدي غازي'),
  ('pdc', 194, 'kafr Al Sheikh', 'Qeleen', 'قلين'),
  ('pdc', 195, 'kafr Al Sheikh', 'Matobus', 'مطوبس'),
  ('pdc', 196, 'kafr Al Sheikh', 'Masseir', 'مسير'),
  ('pdc', 197, 'kafr Al Sheikh', 'Massef Balteem', 'مصيف بلطيم'),
  ('pdc', 198, 'kafr Al Sheikh', 'Kafr Al-sheikh', 'كفر الشيخ'),
  ('pdc', 199, 'kafr Al Sheikh', 'Fewa', 'فوه'),
  ('pdc', 200, 'kafr Al Sheikh', 'Borg Al Broloss', 'برج البرلس'),
  ('pdc', 201, 'kafr Al Sheikh', 'Bella', 'بيلا'),
  ('pdc', 202, 'kafr Al Sheikh', 'Balteem', 'بلطيم'),
  ('pdc', 203, 'kafr Al Sheikh', 'Al reyad', 'الرياض'),
  ('pdc', 204, 'kafr Al Sheikh', 'Al hamoul', 'الحامول'),
  ('pdc', 205, 'Port Said', 'Port Said', 'بورسعيد'),
  ('pdc', 206, 'Port Said', 'Port Fouad', 'بورفؤاد'),
  ('pdc', 207, 'Port Said', 'Sharq-e-Tafrea''a', 'شرق التفريعة'),
  ('pdc', 208, 'Qalyubia', 'Toukh', 'طوخ'),
  ('pdc', 209, 'Qalyubia', 'Shoubra Alkhaima', 'شبرا الخيمة'),
  ('pdc', 210, 'Qalyubia', 'Shebeen Alqanater', 'شبين القناطر'),
  ('pdc', 211, 'Qalyubia', 'Qaliub', 'قليوب'),
  ('pdc', 212, 'Qalyubia', 'Qaha', 'قها'),
  ('pdc', 213, 'Qalyubia', 'Kanater Khairia', 'القناطر الخيرية'),
  ('pdc', 214, 'Qalyubia', 'Kafr Shoukr', 'كفر شكر'),
  ('pdc', 215, 'Qalyubia', 'Banha', 'بنها'),
  ('pdc', 216, 'Qalyubia', 'Alobour', 'العبور'),
  ('pdc', 217, 'Qalyubia', 'Alkhanka', 'الخانكة'),
  ('pdc', 218, 'Qalyubia', 'Al Khousoss', 'الخصوص'),
  ('pdc', 219, 'Qalyubia', 'Qalyubia', 'القليوبية'),
  ('pdc', 220, 'Suez', 'Suez', 'السويس'),
  ('pdc', 221, 'Suez', 'Al Soukhna', 'السخنة'),
  ('pdc', 222, 'Suez', 'El Ganayen', 'الجناين'),
  ('pdc', 223, 'Alfayoum', 'Youssef Alsedeik', 'يوسف الصديق'),
  ('pdc', 224, 'Alfayoum', 'waadi al rayaan', 'وادي الريان'),
  ('pdc', 225, 'Alfayoum', 'Tamiea', 'طامية'),
  ('pdc', 226, 'Alfayoum', 'Snourss', 'سنورس'),
  ('pdc', 227, 'Alfayoum', 'madinat alfayuwm aljadida', 'مدينة الفيوم الجديدة'),
  ('pdc', 228, 'Alfayoum', 'Itsa', 'إطسا'),
  ('pdc', 229, 'Alfayoum', 'Abshuaa', 'إبشواي'),
  ('pdc', 230, 'Alfayoum', 'Alfayoum', 'الفيوم'),
  ('pdc', 231, 'Assiut', 'Sahel Seleim', 'ساحل سليم'),
  ('pdc', 232, 'Assiut', 'Sadfaa', 'صدفا'),
  ('pdc', 233, 'Assiut', 'Manfalout', 'منفلوط'),
  ('pdc', 234, 'Assiut', 'Dairout', 'ديروط'),
  ('pdc', 235, 'Assiut', 'Assiut Algedida', 'أسيوط الجديدة'),
  ('pdc', 236, 'Assiut', 'Assiut', 'أسيوط'),
  ('pdc', 237, 'Assiut', 'Alzaheir Alsahrawy', 'الظهير الصحراوي'),
  ('pdc', 238, 'Assiut', 'Alqossya', 'القوصية'),
  ('pdc', 239, 'Assiut', 'Alghaniem', 'الغنايم'),
  ('pdc', 240, 'Assiut', 'Alfath', 'الفتح'),
  ('pdc', 241, 'Assiut', 'Albadry', 'البداري'),
  ('pdc', 242, 'Assiut', 'Abu Teih', 'أبو تيج'),
  ('pdc', 243, 'Assiut', 'Abnoob', 'أبنوب'),
  ('pdc', 244, 'Beni Suef', 'Smastta', 'سمسطا'),
  ('pdc', 245, 'Beni Suef', 'Nasser', 'ناصر'),
  ('pdc', 246, 'Beni Suef', 'Ihnassya', 'إهناسيا'),
  ('pdc', 247, 'Beni Suef', 'Ben Suief Algedida', 'بني سويف الجديدة'),
  ('pdc', 248, 'Beni Suef', 'Ben Suief', 'بني سويف'),
  ('pdc', 249, 'Beni Suef', 'Biba', 'ببا'),
  ('pdc', 250, 'Beni Suef', 'Alwastta', 'الواسطي'),
  ('pdc', 251, 'Beni Suef', 'Alfeshin', 'الفشن'),
  ('pdc', 252, 'El Menia', 'Samalout', 'سمالوط'),
  ('pdc', 253, 'El Menia', 'Mattay', 'مطاي'),
  ('pdc', 254, 'El Menia', 'Malawy', 'ملوي'),
  ('pdc', 255, 'El Menia', 'Maghagha', 'مغاغة'),
  ('pdc', 256, 'El Menia', 'El Menia  Algedida', 'المنيا الجديدة'),
  ('pdc', 257, 'El Menia', 'El Menia', 'المنيا'),
  ('pdc', 258, 'El Menia', 'Dirmouass', 'ديرمواس'),
  ('pdc', 259, 'El Menia', 'Bani Mazar', 'بني مزار'),
  ('pdc', 260, 'El Menia', 'Aladwa', 'العدوة'),
  ('pdc', 261, 'El Menia', 'Abu Qorqass', 'أبو قرقاص'),
  ('pdc', 262, 'Aswan', 'New toushka City', 'توشكى الجديدة'),
  ('pdc', 263, 'Aswan', 'New Aswan City', 'أسوان الجديدة'),
  ('pdc', 264, 'Aswan', 'Nassr Alnouba', 'نصر النوبة'),
  ('pdc', 265, 'Aswan', 'Kom Ambo', 'كوم أمبو'),
  ('pdc', 266, 'Aswan', 'Kalabsha', 'كلابشة'),
  ('pdc', 267, 'Aswan', 'Edfo', 'إدفو'),
  ('pdc', 268, 'Aswan', 'Drawo', 'دراو'),
  ('pdc', 269, 'Aswan', 'Aswan', 'أسوان'),
  ('pdc', 270, 'Aswan', 'Alsabaia', 'السباعية'),
  ('pdc', 271, 'Aswan', 'Albesaila', 'البصيلية'),
  ('pdc', 272, 'Aswan', 'Al Radessa', 'الرديسية'),
  ('pdc', 273, 'Aswan', 'Abu Sembal Alsayhia', 'أبو سمبل السياحية'),
  ('pdc', 274, 'Aswan', 'Abu Sembal', 'أبو سمبل'),
  ('pdc', 275, 'Aswan', 'Toshka', 'توشكى'),
  ('pdc', 276, 'Luxor', 'Teiba Algedida', 'طيبة الجديدة'),
  ('pdc', 277, 'Luxor', 'Luxor Algedida', 'الأقصر الجديدة'),
  ('pdc', 278, 'Luxor', 'Luxor', 'الأقصر'),
  ('pdc', 279, 'Luxor', 'Issna', 'إسنا'),
  ('pdc', 280, 'Luxor', 'Armant', 'أرمنت'),
  ('pdc', 281, 'Luxor', 'Altoud', 'الطود'),
  ('pdc', 282, 'Luxor', 'Alqarna', 'القرنة'),
  ('pdc', 283, 'Luxor', 'Al Zeinya', 'الزينية'),
  ('pdc', 284, 'Luxor', 'Al bayada', 'البياضية'),
  ('pdc', 285, 'Qena', 'Quoss', 'قوص'),
  ('pdc', 286, 'Qena', 'Qena Algedida', 'قنا الجديدة'),
  ('pdc', 287, 'Qena', 'Qena', 'قنا'),
  ('pdc', 288, 'Qena', 'Qaft', 'قفط'),
  ('pdc', 289, 'Qena', 'Naqada', 'نقادة'),
  ('pdc', 290, 'Qena', 'Naga Hamadi', 'نجع حمادي'),
  ('pdc', 291, 'Qena', 'Farshout', 'فرشوط'),
  ('pdc', 292, 'Qena', 'Dashna', 'دشنا'),
  ('pdc', 293, 'Qena', 'Alwakf', 'الوقف'),
  ('pdc', 294, 'Qena', 'Abu tesht', 'أبو تشت'),
  ('pdc', 295, 'Red Sea', 'Safaja', 'سفاجا'),
  ('pdc', 296, 'Red Sea', 'Ras Gharib', 'رأس غارب'),
  ('pdc', 297, 'Red Sea', 'Marsa Allam', 'مرسى علم'),
  ('pdc', 298, 'Red Sea', 'Hurghada', 'الغردقة'),
  ('pdc', 299, 'Red Sea', 'Halyeb', 'حلايب'),
  ('pdc', 300, 'Red Sea', 'Alqussier', 'القصير'),
  ('pdc', 301, 'Red Sea', 'Al shalatten', 'الشلاتين'),
  ('pdc', 302, 'Red Sea', 'Red Sea', 'البحر الأحمر'),
  ('pdc', 303, 'Sohag', 'Tama', 'طما'),
  ('pdc', 304, 'Sohag', 'Tahtaa', 'طهطا'),
  ('pdc', 305, 'Sohag', 'Suhag', 'سوهاج'),
  ('pdc', 306, 'Sohag', 'Saqalta', 'ساقلتة'),
  ('pdc', 307, 'Sohag', 'Hay Alqawssar', 'حي الكوثر'),
  ('pdc', 308, 'Sohag', 'Gouhaina', 'جهينة'),
  ('pdc', 309, 'Sohag', 'Gerga', 'جرجا'),
  ('pdc', 310, 'Sohag', 'Dar Alsalam', 'دار السلام'),
  ('pdc', 311, 'Sohag', 'Al manshaa', 'المنشأة'),
  ('pdc', 312, 'Sohag', 'Al Maragha', 'المراغة'),
  ('pdc', 313, 'Sohag', 'Al Ballena', 'البلينا'),
  ('pdc', 314, 'Sohag', 'Akhmiem', 'أخميم'),
  ('pdc', 315, 'New Valley', 'Paris', 'باريس'),
  ('pdc', 316, 'New Valley', 'Pallat', 'بلاط'),
  ('pdc', 317, 'New Valley', 'Mout', 'موط'),
  ('pdc', 318, 'New Valley', 'Al kharga', 'الخارجة'),
  ('pdc', 319, 'New Valley', 'Al Farafra', 'الفرافرة'),
  ('pdc', 320, 'New Valley', 'Siwa', 'سيوة'),
  ('pdc', 321, 'New Valley', 'Kharja Oases', 'واحة الخارجة'),
  ('pdc', 322, 'New Valley', 'Dakhla Oases', 'واحة الداخلة'),
  ('pdc', 323, 'Matrouh', 'North Coast Above 90Km', 'الساحل الشمالي فوق 90 كم'),
  ('pdc', 324, 'Matrouh', 'Um Alrekhim', 'أم الرخم'),
  ('pdc', 325, 'Matrouh', 'Sidi Heneish', 'سيدي حنيش'),
  ('pdc', 326, 'Matrouh', 'Ras Alhikma', 'رأس الحكمة'),
  ('pdc', 327, 'Matrouh', 'Kashuk Emaara', 'كشك عمارة'),
  ('pdc', 328, 'Matrouh', 'Halazein', 'الحلازين'),
  ('pdc', 329, 'Matrouh', 'Awlad Marii', 'أولاد مري'),
  ('pdc', 330, 'Matrouh', 'Atnouh', 'أتنوح'),
  ('pdc', 331, 'Matrouh', 'Al zayat', 'الزيات'),
  ('pdc', 332, 'Matrouh', 'Al suynat', 'السوينات'),
  ('pdc', 333, 'Matrouh', 'Al salom', 'السلام'),
  ('pdc', 334, 'Matrouh', 'Al qawasim', 'القواسم'),
  ('pdc', 335, 'Matrouh', 'Al qasr', 'القصر'),
  ('pdc', 336, 'Matrouh', 'Al oush', 'العوش'),
  ('pdc', 337, 'Matrouh', 'Al nasr', 'النصر'),
  ('pdc', 338, 'Matrouh', 'Al grawla', 'الجراولة'),
  ('pdc', 339, 'Matrouh', 'Al dakhla', 'الداخلة'),
  ('pdc', 340, 'Matrouh', 'Abuluho Alganouby', 'أبو لحو الجنوبي'),
  ('pdc', 341, 'Matrouh', 'Abuluho Albahri', 'أبو لحو البحري'),
  ('pdc', 342, 'Matrouh', 'Abu Mareiq', 'أبو مريق'),
  ('pdc', 343, 'Matrouh', 'Matrouh', 'مطروح'),
  ('pdc', 344, 'Matrouh', 'Al Hammam', 'الحمام'),
  ('pdc', 345, 'Matrouh', 'Al almeen', 'العلمين'),
  ('pdc', 346, 'Matrouh', 'Brani', 'براني'),
  ('pdc', 347, 'Matrouh', 'Negela', 'النجيلة'),
  ('pdc', 348, 'Matrouh', 'Salloum', 'السلوم'),
  ('pdc', 349, 'North Seina', 'Rafah', 'رفح'),
  ('pdc', 350, 'North Seina', 'Bir Alabd', 'بئر العبد'),
  ('pdc', 351, 'North Seina', 'Al sheikh Zwayd', 'الشيخ زويد'),
  ('pdc', 352, 'North Seina', 'Al nakhl', 'النخل'),
  ('pdc', 353, 'North Seina', 'Al hassana', 'الحسنة'),
  ('pdc', 354, 'North Seina', 'Al Aresh', 'العريش'),
  ('pdc', 355, 'North Seina', 'North Sinai', 'شمال سيناء'),
  ('pdc', 356, 'South Seina', 'Tor Sinai', 'طور سيناء'),
  ('pdc', 357, 'South Seina', 'Taba', 'طابا'),
  ('pdc', 358, 'South Seina', 'Sharm Alsheikh', 'شرم الشيخ'),
  ('pdc', 359, 'South Seina', 'Saint Katreen', 'سانت كاترين'),
  ('pdc', 360, 'South Seina', 'Rass Sudr', 'رأس سدر'),
  ('pdc', 361, 'South Seina', 'Nwabea', 'نويبع'),
  ('pdc', 362, 'South Seina', 'Dahab', 'دهب'),
  ('pdc', 363, 'South Seina', 'Abu Zeniema', 'أبو زنيمة'),
  ('pdc', 364, 'South Seina', 'Abu Redeis', 'أبو رديس'),
  ('pdc', 365, 'South Seina', 'South Sinai', 'جنوب سيناء'),
  ('pdc', 366, 'Cairo 2', 'Others', 'أخرى'),
  ('pdc', 367, 'Cairo 2', 'New capital', 'العاصمة الإدارية الجديدة'),
  ('pdc', 368, 'Cairo 2', 'Manshiat Nasr', 'منشأة ناصر'),
  ('pdc', 369, 'Cairo 2', 'Al Waily', 'الوايلي'),
  ('pdc', 370, 'Cairo 2', 'Al Marg', 'المرج'),
  ('pdc', 371, 'Cairo 2', 'Al Zawya Elhamra', 'الزاوية الحمراء'),
  ('pdc', 372, 'Giza 2', 'Al badrasheen', 'البدرشين'),
  ('pdc', 373, 'Giza 2', 'Kerdassa', 'كرداسة'),
  ('pdc', 374, 'Giza 2', 'Al Hawamdia', 'الحوامدية'),
  ('pdc', 375, 'Giza 2', 'Al Wahat city', 'مدينة الواحات'),
  ('pdc', 376, 'Giza 2', 'Atfeh', 'أطفيح'),
  ('pdc', 377, 'Giza 2', 'Alsaff', 'الصف'),
  ('pdc', 378, 'Giza 2', 'Monshaet Alqanater', 'منشأة القناطر'),
  ('pdc', 379, 'Giza 2', 'Alayaat', 'العياط'),
  ('pdc', 380, 'Giza 2', 'Awssem', 'أوسيم'),
  ('pdc', 381, 'Giza 2', 'Abo AlNomross', 'أبو النمرس'),
  ('pdc', 382, 'Giza 2', 'Al barageel', 'البراجيل')
on conflict (provider, provider_city_id) do update
set
  governorate = excluded.governorate,
  city = excluded.city,
  city_arabic = excluded.city_arabic,
  updated_at = now();

commit;
